FROM rigon/photo-gallery:latest

RUN set -- Nature Film Animals Travel People "Machu Picchu" "The Grand Canyon" "Great Barrier Reef" Maldives Paris Iceland \
        Wallpapers/Moutains Wallpapers/Rivers Wallpapers/Lanscapes Wallpapers/Abstract Wallpapers/Gradients Wallpapers/Patterns; \
    for term in "$@"; do \
        mkdir -p "/photos/$term"; \
        for i in $(seq 1 50); do wget -O "/photos/$term/$i.jpg" "https://source.unsplash.com/random?$(echo $term | sed 's/ /%20/g')"; done; \
    done
